### ISSUE TITLE
Nginx config and secure links

### ISSUE THREAD

**Issue by cronner** [avscms/avscms#1]
Would be really nice with some nginx configuration and secure links http://nginx.org/en/docs/http/ngx_http_secure_link_module.html

**Comment by boonacb** [comment]
will add nginx secure link documentation.

**Comment by hassaan-dev** [comment]
> will add nginx secure link documentation.

@boonacb have you added this documentation? if yes, then from where I can get that?

**Comment by cronner** [comment]
is it somewhere since it's closed?
