### ISSUE TITLE
Hello Support !

### ISSUE THREAD

**Issue by desireyes** [avscms/avscms#11]
Is there anybody for the support from the AVS?
I left a ticket on helpdesk on 7th of this month, but no reply yet.
:(

**Comment by cronner** [comment]
hmm i sure hope so should be a new owner, some of the plugins need some work and they still change for them.

**Comment by desireyes** [comment]
I hope this new owner knows what he's doing.
Old forum was good and there were lots of users, so someone always helped.
Boon was good at the help desk and got the fixes pretty fast.
Let's see what happens to this script.

**Comment by cronner** [comment]
yeah to bad they closed the forum, alot of help and code, like RSS, nginx secure links etc.

**Comment by desireyes** [comment]
Are you running 8.2 or previous version?

**Comment by cronner** [comment]
I'm running 8.2, new install

**Comment by boonacb** [comment]
@desireyes your ticket has been answered
