### ISSUE TITLE
All templates except index.tpl broken

### ISSUE THREAD

**Issue by Carottinger** [avscms/avscms#13]
I am taking over an avs project that basically ran before but since I restarted the server (and re-assigned its former DNS name only the start Page (index.php/tpl) works. Any link (e.g. clicking on a video -> video.php/tpl) will result in a 404 even though the underlying media is present.

Any idea how I could debug this?

**Comment by cronner** [comment]
could be a Apache/Nginx rewrite problem

**Comment by Carottinger** [comment]
What can I do?

**Comment by cronner** [comment]
make sure webserver and php-fpm is running with the correct rewrite acording to install guide

**Comment by Carottinger** [comment]
nginx restart and config update worked
