### ISSUE TITLE
VirusTotal detecting 2 possible trojans in this project

### ISSUE THREAD

**Issue by entronn** [avscms/avscms#3]
Why VirusTotal detecting 2 possible trojans in this project?

<img width="1434" alt="avs" src="https://github.com/avscms/avscms/assets/126366243/ffd85f0d-0cdb-4ee0-af8e-8de8d6a0e305">

**Comment by cronner** [comment]
8.1 is clean according to scan 8.2 is not

**Comment by entronn** [comment]
> 

why so? Any idea?

**Comment by cronner** [comment]
nope I can't find the specific  files with the online scanner
maybe it's "Player source encrypted and protected" but need to be adressed by author

**Comment by entronn** [comment]
Problem is in this file : /language/hu_HU.lang.php 

<img width="1429" alt="hu_HU lang php" src="https://github.com/avscms/avscms/assets/126366243/4cd4c3d6-15fd-4a8c-9905-b06b70457c2c">

**Comment by cronner** [comment]
yeah there is some code in there that should not be there

**Comment by entronn** [comment]
Yes

**Comment by avscms** [comment]
issue confirmed and fixed
