### ISSUE TITLE
Conversion Queue bug

### ISSUE THREAD

**Issue by cronner** [avscms/avscms#7]
The conversion queue is set to 1 but it converts 2 videos at a time, seems like it does one 1st pass and one 2pass at the same time despite set to 1. 
[https://postimg.cc/gallery/sXZvkNX](url)

**Comment by boonacb** [comment]
please submit your login info at helpdesk.adultvideoscript.com for further check.

**Comment by cronner** [comment]
I works fine untill 2 pass, then it starts a new 1 pass, no need for login, it's a clean install.
